package constants

var CurrencyDict = map[string]map[string]string{
	"USD": {"en": "US Dollar", "th": "ดอลลาร์สหรัฐ"},
	"EUR": {"en": "Euro", "th": "ยูโร"},
	"JPY": {"en": "Japanese Yen", "th": "เยนญี่ปุ่น"},
	"GBP": {"en": "British Pound Sterling", "th": "ปอนด์สเตอร์ลิงอังกฤษ"},
	"AUD": {"en": "Australian Dollar", "th": "ดอลลาร์ออสเตรเลีย"},
	"CAD": {"en": "Canadian Dollar", "th": "ดอลลาร์แคนาดา"},
	"CHF": {"en": "Swiss Franc", "th": "ฟรังก์สวิส"},
	"CNY": {"en": "Chinese Yuan", "th": "หยวนจีน"},
	"SEK": {"en": "Swedish Krona", "th": "โครนาสวีเดน"},
	"NZD": {"en": "New Zealand Dollar", "th": "ดอลลาร์นิวซีแลนด์"},
	"MXN": {"en": "Mexican Peso", "th": "เปโซเม็กซิโก"},
	"INR": {"en": "Indian Rupee", "th": "รูปีอินเดีย"},
	"SGD": {"en": "Singapore Dollar", "th": "ดอลลาร์สิงคโปร์"},
	"HKD": {"en": "Hong Kong Dollar", "th": "ดอลลาร์ฮ่องกง"},
	"NOK": {"en": "Norwegian Krone", "th": "โครนานอร์เวย์"},
	"KRW": {"en": "South Korean Won", "th": "วอนเกาหลีใต้"},
	"TRY": {"en": "Turkish Lira", "th": "ลีร่าตุรกี"},
	"RUB": {"en": "Russian Ruble", "th": "รูเบิลรัสเซีย"},
	"ZAR": {"en": "South African Rand", "th": "แรนด์แอฟริกาใต้"},
	"THB": {"en": "Thai Baht", "th": "บาทไทย"},
	"MYR": {"en": "Malaysian Ringgit", "th": "ริงกิตมาเลเซีย"},
	"IDR": {"en": "Indonesian Rupiah", "th": "รูเปียห์อินโดนีเซีย"},
	"BRL": {"en": "Brazilian Real", "th": "เรียลบราซิล"},
	"SAR": {"en": "Saudi Riyal", "th": "ริยาลซาอุดีอาระเบีย"},
	"ARS": {"en": "Argentine Peso", "th": "เปโซอาร์เจนตินา"},
	"AED": {"en": "UAE Dirham", "th": "ดีรัมสหรัฐอาหรับเอมิเรตส์"},
	"ILS": {"en": "Israeli New Shekel", "th": "เชเคลใหม่อิสราเอล"},
	"DKK": {"en": "Danish Krone", "th": "โครนาดานมาร์ก"},
	"PLN": {"en": "Polish Zloty", "th": "สลอตี้โปแลนด์"},
	"HUF": {"en": "Hungarian Forint", "th": "ฟอรินต์ฮังการี"},
	"CZK": {"en": "Czech Koruna", "th": "โครนาสาธารณรัฐเช็ก"},
	"BGN": {"en": "Bulgarian Lev", "th": "เลฟบัลแกเรีย"},
	"RON": {"en": "Romanian Leu", "th": "เลูโรมาเนีย"},
	"KWD": {"en": "Kuwaiti Dinar", "th": "ดินาร์คูเวต"},
	"OMR": {"en": "Omani Rial", "th": "เรียลโอมาน"},
	"JOD": {"en": "Jordanian Dinar", "th": "ดินาร์จอร์แดน"},
	"QAR": {"en": "Qatari Rial", "th": "เรียลกาตาร์"},
	"LBP": {"en": "Lebanese Pound", "th": "ปอนด์เลบานอน"},
	"EGP": {"en": "Egyptian Pound", "th": "ปอนด์อียิปต์"},
	"VND": {"en": "Vietnamese Dong", "th": "ดงเวียดนาม"},
	"CLP": {"en": "Chilean Peso", "th": "เปโซชิลี"},
	"PEN": {"en": "Peruvian Nuevo Sol", "th": "นูเอโวโซลเปรู"},
	"COP": {"en": "Colombian Peso", "th": "เปโซโคลอมเบีย"},
	"BWP": {"en": "Botswana Pula", "th": "พูลาบอตสวานา"},
	"LKR": {"en": "Sri Lankan Rupee", "th": "รูปีศรีลังกา"},
	"MNT": {"en": "Mongolian Tugrik", "th": "ตุกริกมองโกเลีย"},
	"UGX": {"en": "Ugandan Shilling", "th": "ชิลลิงยูกันดา"},
	"PKR": {"en": "Pakistani Rupee", "th": "รูปีปากีสถาน"},
	"KES": {"en": "Kenyan Shilling", "th": "ชิลลิงเคนยา"},
	"MMK": {"en": "Myanmar Kyat", "th": "เกียตพม่า"},
	"KHR": {"en": "Cambodian Riel", "th": "เรียลกัมพูชา"},
	"NPR": {"en": "Nepalese Rupee", "th": "รูปีเนปาล"},
}
